# Generated by Django 5.0.2 on 2025-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('status', models.CharField(default='ativo', max_length=10)),
                ('role', models.CharField(choices=[('Paciente', 'Paciente'), ('Medico', 'Médico')], default='Paciente', max_length=10)),
                ('crm', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
