# Generated by Django 5.0.2 on 2025-03-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='crm',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
