# Generated by Django 5.0.2 on 2025-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0002_alter_usuario_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='crm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
