# Generated by Django 5.0.2 on 2025-03-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0005_alter_usuario_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='crp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Psiquiatra', 'Psiquiatra'), ('Psicologo', 'Psicólogo')], default='Paciente', max_length=10),
        ),
    ]
