# Generated by Django 5.0.2 on 2025-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0006_usuario_crp_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('Paciente', 'Paciente'), ('Psiquiatra', 'Psiquiatra'), ('Psicologo', 'Psicólogo'), ('Admin', 'Admin')], default='Paciente', max_length=10),
        ),
    ]
