# Generated by Django 5.0.2 on 2025-05-07 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0007_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('link_consulta', models.URLField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('psiquiatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_psiquiatra', to='app_projeto.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to='app_projeto.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('data_status', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto.agendamento')),
            ],
        ),
    ]
