# Generated by Django 5.2 on 2025-06-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0009_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios_fotos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
