# Generated by Django 5.2 on 2025-06-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0010_usuario_foto_usuario_valor_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID da conta Stripe Connect do profissional', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_email',
            field=models.EmailField(blank=True, help_text='E-mail da conta Stripe do profissional', max_length=254, null=True),
        ),
    ]
