# Generated by Django 5.2 on 2025-06-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0011_usuario_stripe_account_id_usuario_stripe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='payment_intent',
            field=models.CharField(blank=True, help_text='ID do PaymentIntent do Stripe', max_length=255, null=True),
        ),
    ]
