# Generated by Django 5.2 on 2025-06-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0012_agendamento_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='payment_intent',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='stripe_email',
        ),
    ]
