# Generated by Django 5.2 on 2025-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0013_remove_agendamento_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='stripe_email',
            field=models.EmailField(blank=True, help_text='E-mail da conta Stripe do profissional', max_length=254, null=True),
        ),
    ]
