# Generated by Django 5.2 on 2025-06-15 16:51

import app_projeto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0015_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=app_projeto.models.user_foto_upload_path),
        ),
    ]
