# Generated by Django 5.2 on 2025-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0016_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID da conta Stripe Connect', max_length=255, null=True),
        ),
    ]
