# Generated by Django 5.2 on 2025-06-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0017_usuario_stripe_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='stripe_email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_access_token',
            field=models.CharField(blank=True, help_text='Access Token Mercado Pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_user_id',
            field=models.CharField(blank=True, help_text='ID da conta Mercado Pago Connect', max_length=255, null=True),
        ),
    ]
