# Generated by Django 5.2 on 2025-06-25 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0018_remove_usuario_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_psicologo', to='app_projeto.usuario'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='psiquiatra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_psiquiatra', to='app_projeto.usuario'),
        ),
    ]
