# Generated by Django 5.2 on 2025-08-08 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0019_agendamento_psicologo_alter_agendamento_psiquiatra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mp_access_token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mp_user_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID da conta Stripe Connect', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_email',
            field=models.EmailField(blank=True, help_text='E-mail da conta Stripe do profissional', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='app_projeto.agendamento')),
            ],
        ),
    ]
