# Generated by Django 5.2 on 2025-08-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0020_remove_usuario_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_plataforma',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor recebido pela plataforma (R$)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_recebido_profissional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor recebido pelo profissional (R$)', max_digits=10, null=True),
        ),
    ]
