# Generated by Django 5.2 on 2025-08-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0022_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='ID da sessão Stripe para refund', max_length=255, null=True),
        ),
    ]
