# Generated by Django 5.2 on 2025-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0023_agendamento_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Consulta paga'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamentohistorico',
            name='status_anterior',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Consulta paga'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
