# Generated by Django 5.2 on 2025-08-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0024_alter_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='mensagem_paciente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
