# Generated by Django 5.2 on 2025-09-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0025_prontuario_mensagem_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
