# Generated by Django 5.2 on 2025-09-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0026_agendamento_reminder_24h_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='reminder_24h_sent',
        ),
    ]
