# Generated by Django 5.2 on 2025-09-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0027_remove_agendamento_reminder_24h_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='atestado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prontuarios/atestados/'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='receita_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prontuarios/receitas/'),
        ),
    ]
