# Generated by Django 5.2 on 2025-09-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0028_prontuario_atestado_pdf_prontuario_receita_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(limit_choices_to={'role__in': ['Psiquiatra', 'Psicologo']}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='app_projeto.usuario')),
            ],
            options={
                'ordering': ['profissional', 'dia_semana', 'horario_inicio'],
                'unique_together': {('profissional', 'dia_semana', 'horario_inicio', 'horario_fim')},
            },
        ),
    ]
