"""
Django settings for back_projeto project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# JWT Signature Verification do JWT
SECRET_KEY = 'django-insecure-zv4!s&j9bpx@rjq=l$*wcmybts&h7#_3sgb(jd07!aa@1$0tk0'

# Remover duplicidade de SECRET_KEY e padronizar uso
# JWT settings para SimpleJWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=240),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,  # Usa o mesmo SECRET_KEY do Django
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'https://70a0ae26b12e.ngrok-free.app',  # altera toda vez que gerar um novo túnel ngrok
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django.contrib.sites',
    'corsheaders',
    'app_projeto',
]


CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    "https://70a0ae26b12e.ngrok-free.app",  # Altere para o seu domínio ngrok
]

# CORS CONFIGURAÇÃO CORRETA
# Eu deixo apenas UMA definição de CORS_ALLOWED_ORIGINS, incluindo localhost e ngrok
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://70a0ae26b12e.ngrok-free.app",  # Altere para o seu domínio ngrok
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'x-csrftoken',
    'Authorization',
]



CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = "X-CSRFToken"  
CSRF_COOKIE_HTTPONLY = False  
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_SECURE = False 
CSRF_USE_SESSIONS = False

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = False

SITE_ID = 1

LOGIN_REDIRECT_URL = '/dashboard/'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #'app_projeto.middlewares.JWTAuthenticationMiddleware',
    # 'app_projeto.middleware.TokenAuthMiddleware',  # Comente temporariamente
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Usa JWT
    ),
}



APPEND_SLASH = False


AUTHENTICATION_BACKENDS = [
    'app_projeto.valida.backends.EmailBackend',   
    'django.contrib.auth.backends.ModelBackend', 
    ]
    


ROOT_URLCONF = 'back_projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back_projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tcc_desabafe',  
        'USER': 'root',          
        'PASSWORD': 'root',  
        'HOST': 'localhost',      
        'PORT': '3306',          
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Configuração de arquivos de mídia (fotos de perfil, etc)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "suportedesabafe@gmail.com"
EMAIL_HOST_PASSWORD = "ejdt ltsw tlzm qouf"
DEFAULT_FROM_EMAIL = "suportedesabafe@gmail.com"